version: 2
jobs:
  build:
    working_directory: ~/code
    machine:
      java:
        version: oraclejdk8
      environment:
        ANDROID_HOME: /home/ubuntu/android
        GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
        TEST_FLAGS: --configure-on-demand -PdisablePreDex
        ADB_INSTALL_TIMEOUT: '10'
    steps:
    - checkout
    - run:
        name: Chmod permissions
        command: sudo chmod +x ./AndroidDemo/gradlew
    - run:
        name: Download Dependencies
        command: ./AndroidDemo/gradlew dependencies
    - run:
        name: checking java
        command: which java
    - run:
        name: downloading sdk managger
        command: wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - run:
        name: creating andriod folder
        command: mkdir android
    - run:
        name: unzip sdk managger
        command: unzip sdk-tools-linux-4333796.zip    
    - run:
        name: Setup accepting license
        command: yes | ./tools/bin/sdkmanager "system-images;android-25;google_apis;armeabi-v7a" 
    - run:
        name: set up 
        command: echo "no" | ./tools/bin/avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"    
    - run:
        name: Launch emulator
        command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
        background: true
    - run:
        name: Wait emulator
        command: |
          # wait for it to have booted
          circle-android wait-for-boot
          # unlock the emulator screen
          sleep 30
          adb shell input keyevent 82
    - run:
        name: Run Tests
        command: ./AndroidDemo/gradlew CallOnDriverNumberScenario
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
workflows:
  version: 2
  workflow:
    jobs:
    - build