version: 2
jobs:
  build:
    working_directory: ~/code
    machine:
     java:
    #Because buildtools 24.0.2 and above require Java 1.8 or above
       version: oraclejdk8
     environment:
    #Necessary for the Android SDKs to function properly. Also useful for booting up the emulator in later steps
      ANDROID_HOME: /home/ubuntu/android
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      TEST_FLAGS: "--configure-on-demand -PdisablePreDex"
      ADB_INSTALL_TIMEOUT: "10"
    steps:
      - checkout
     # - restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./AndroidDemo/gradlew
      - run:
          name: Download Dependencies
          command: ./AndroidDemo/gradlew dependencies
      #- save_cache:
         # paths:
       #     - ~/.gradle
       #   key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: checking java
          command: which java
      - run:
          name: downloading sdk managger
          command: wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      - run:
          name: creating andriod folder
          command: mkdir android
      - run:
          name: unzip sdk managger
          command: unzip sdk-tools-linux-4333796.zip 
      - run:
          name: list folders 
          command: ls -la             
                
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./AndroidDemo/gradlew ExampleInstrumentedTest 
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
